import type { Locale } from './routes'

const hr = {
  shop: 'Trgovina',
  allCases: 'Kolekcija',
  cart: 'Košarica',
  checkout: 'Blagajna',
  account: 'Moj račun',
  favorites: 'Favoriti',
  login: 'Prijava',
  logout: 'Odjava',
  register: 'Registracija',
  menu: 'Izbornik',
  close: 'Zatvori',
  addToCart: 'Dodaj u košaricu',
  added: 'Dodano',
  outOfStock: 'Nema na zalihi',
  qty: 'Količina',
  subtotal: 'Međuzbroj',
  shipping: 'Dostava',
  free: 'Besplatno',
  total: 'Ukupno',
  continueShopping: 'Nastavi kupovinu',
  emptyCart: 'Košarica je prazna.',
  goToCheckout: 'Na blagajnu',
  viewCart: 'Pogledaj košaricu',
  remove: 'Ukloni',
  variant: 'Dostupna veličina',
  fits: 'Odgovara',
  description: 'Opis',
  details: 'Detalji',
  material: 'Materijal',
  delivery: 'Dostava',
  deliveryTime: 'Rok dostave',
  productSafety: 'Sigurnost proizvoda',
  manufacturer: 'Proizvođač',
  euResponsible: 'Odgovorna osoba u EU',
  safetyInfo: 'Upozorenja i sigurnosne informacije',
  sku: 'Šifra',
  lowest30: 'Najniža cijena u zadnjih 30 dana',
  freeOver: (a: string) => `Besplatna dostava za narudžbe iznad ${a}`,
  freeLeft: (a: string) => `Još ${a} do besplatne dostave`,
  freeReached: 'Ostvarili ste besplatnu dostavu',
  all: 'Sve',
  sortFeatured: 'Istaknuto',
  sortPriceAsc: 'Cijena ↑',
  sortPriceDesc: 'Cijena ↓',
  viewAll: 'Pogledaj sve',
  noProducts: 'Trenutno nema proizvoda.',
  heroEyebrow: 'Futrole za upaljače',
  heroPre: 'Pauza za cigaretu,',
  heroEm: 's više',
  heroPost: 'stila.',
  heroSub: 'Futrolu navučete na svoj upaljač za par sekundi. Čuva ga od ogrebotina, a običan upaljač napokon izgleda kao nešto što ste birali.',
  heroCta: 'Istražite kolekciju',
  storyA: 'Upaljač vadite iz džepa više puta dnevno.',
  storyB: 'Red je da i izgleda dobro.',
  faqT: 'Česta pitanja',
  faq: [
    ['Kako znam koja mi veličina treba?', 'Na stranici proizvoda piše za koji je upaljač koja veličina. Ako niste sigurni, pošaljite nam e-mail prije narudžbe pa ćemo vam reći.'],
    ['Koliko traje dostava?', 'Rok piše na stranici proizvoda. Kad paket krene, dobit ćete e-mail.'],
    ['Mogu li vratiti futrolu?', 'Možete, u roku od 14 dana od primitka i bez objašnjavanja zašto. Upute su na stranici Povrat i reklamacije.'],
    ['Je li plaćanje sigurno?', 'Plaćanje ide preko Stripea. Mi podatke vaše kartice ne vidimo i ne spremamo.'],
  ] as [string, string][],
  sizes: (n: number) => `${n} ${n % 10 === 1 && n % 100 !== 11 ? 'veličina' : n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14) ? 'veličine' : 'veličina'}`,
  ret14: '14 dana za povrat',
  related: 'Još iz kolekcije',
  contents: 'Sadržaj',
  returnLabel: 'Povrat',
  returnValue: '14 dana, bez objašnjenja',
  shopIntro: 'Sve futrole na jednom mjestu. Veličinu za svoj upaljač birate na stranici proizvoda.',
  footerTag: 'Vaš upaljač, vaš stil.',
  footerShop: 'Kupovina',
  footerInfo: 'Informacije',
  footerCompany: 'Prodavatelj',
  payments: 'Kartice · Apple Pay · Google Pay · PayPal',
  terms: 'Uvjeti poslovanja',
  privacy: 'Politika privatnosti',
  cookies: 'Kolačići',
  shippingPage: 'Dostava',
  returns: 'Povrat i reklamacije',
  withdrawal: 'Obrazac za jednostrani raskid',
  contact: 'Kontakt',
  // blagajna
  contactDetails: 'Kontakt podaci',
  deliveryAddress: 'Adresa dostave',
  name: 'Ime i prezime',
  email: 'E-mail',
  phone: 'Mobitel (za dostavu)',
  address: 'Ulica i kućni broj',
  city: 'Grad',
  postal: 'Poštanski broj',
  country: 'Država',
  note: 'Napomena (neobavezno)',
  saveDetails: 'Spremi podatke na moj račun',
  acceptTermsPre: 'Pročitao/la sam i prihvaćam ',
  acceptTermsMid: ' te sam upoznat/a s ',
  acceptTermsPost: '.',
  withdrawalInfo: 'informacijama o pravu na jednostrani raskid ugovora',
  orderButton: 'Naruči s obvezom plaćanja',
  payNote: 'Nakon klika preusmjeravamo vas na sigurno plaćanje (Stripe). Ugovor je sklopljen kad plaćanje bude potvrđeno.',
  orderSummary: 'Pregled narudžbe',
  // narudžba
  thanks: 'Hvala na narudžbi!',
  orderNo: 'Narudžba',
  orderPaidText: 'Plaćanje je potvrđeno. Potvrdu i račun poslali smo na vaš e-mail.',
  orderPendingText: 'Čekamo potvrdu plaćanja. Osvježite stranicu za nekoliko trenutaka.',
  orderCancelledText: 'Narudžba je otkazana.',
  downloadInvoice: 'Preuzmi račun (PDF)',
  status: {
    pending: 'Čeka plaćanje', paid: 'Plaćeno', shipped: 'Poslano', delivered: 'Dostavljeno', cancelled: 'Otkazano', refunded: 'Novac vraćen',
  } as Record<string, string>,
  // račun korisnika
  myOrders: 'Moje narudžbe',
  noOrders: 'Još nemate narudžbi.',
  myDetails: 'Moji podaci',
  save: 'Spremi',
  saved: 'Spremljeno.',
  password: 'Lozinka',
  passwordHint: 'Najmanje 8 znakova',
  newPassword: 'Nova lozinka',
  forgot: 'Zaboravljena lozinka?',
  sendLink: 'Pošalji poveznicu',
  linkSent: 'Ako račun postoji, poslali smo poveznicu na e-mail.',
  resetDone: 'Lozinka je promijenjena. Možete se prijaviti.',
  noAccount: 'Nemate račun?',
  haveAccount: 'Već imate račun?',
  createAccount: 'Izradi račun',
  deleteAccount: 'Obriši račun',
  deleteWarn: 'Brisanje je trajno. Podaci o narudžbama čuvaju se koliko to zakon nalaže (računi).',
  noFavorites: 'Nemate spremljenih favorita.',
  addFav: 'Dodaj u favorite',
  removeFav: 'Ukloni iz favorita',
  loginToFav: 'Prijavite se za spremanje favorita',
  cookieText: 'Koristimo nužne kolačiće za rad stranice te, uz vašu privolu, analitičke kolačiće (Google Analytics) kako bismo poboljšali stranicu.',
  cookieTextBasic: 'Koristimo samo nužne kolačiće za rad stranice (prijava, košarica).',
  acceptAll: 'Prihvati sve',
  rejectAll: 'Samo nužni',
  cookieSettings: 'Postavke kolačića',
  ok: 'U redu',
  more: 'Više',
  mailOrderReceivedSubject: 'Vaša narudžba je zaprimljena',
  mailOrderShippedSubject: 'Vaša narudžba je poslana',
  mailOrderNo: (id: number) => `Narudžba #${id}`,
  mailOrderReceivedLead: 'Plaćanje je potvrđeno. U privitku je fiskalizirani račun u PDF-u.',
  mailOrderShippedLead: 'Vaša narudžba je poslana i uskoro stiže na adresu.',
  mailItems: 'Artikli',
  mailDeliveryAddress: 'Adresa dostave',
  mailShipping: 'Dostava',
  mailTotal: 'Ukupno',
  mailCarrier: 'Dostavna služba',
  mailTrackingNo: 'Broj za praćenje',
  mailTrackPackage: 'Prati pošiljku',
  mailViewOrder: 'Pregled narudžbe',
  mailWithdrawalNote:
    'Pravo na jednostrani raskid ugovora: ugovor možete raskinuti u roku od 14 dana od primitka robe bez navođenja razloga. Detalji su u Uvjetima poslovanja. Račun je u privitku.',
  mailSupplierShipNote:
    'Paket se šalje izravno iz skladišta dobavljača. Dostava može potrajati duže nego kod klasične pošte; očekivani rok dostave naveden je u potvrdi narudžbe i na stranici Dostava.',
  mailDeliveryEstimate: (text: string) => `Očekivani rok dostave: ${text}.`,
  mailRefundSubject: (id: number) => `Povrat novca za narudžbu #${id} – Firecase`,
  mailRefundLead: (amount: string, id: number) =>
    `Iznos od ${amount} za narudžbu #${id} vraćen je na vaše izvorno sredstvo plaćanja. Storno račun je u privitku.`,
  mailResetSubject: 'Postavljanje nove lozinke – Firecase',
  mailResetLead: 'Kliknite gumb za postavljanje nove lozinke. Poveznica vrijedi 1 sat.',
  mailResetIgnore: 'Ako niste zatražili promjenu, zanemarite ovaj e-mail.',
  mailOtpSubject: 'Vaš kod za prijavu – Firecase',
  mailOtpPreview: 'Kod za prijavu na Firecase',
  mailOtpTitle: 'Kod za prijavu',
  mailOtpLead: 'Unesite ovaj kod na stranici za prijavu ili registraciju. Nitko ga ne dijelite s drugima.',
  mailOtpExpiry: 'Kod vrijedi 10 minuta.',
  mailOtpIgnore: 'Ako niste zatražili kod, zanemarite ovaj e-mail.',
  mailOtpSent: 'Ako možemo poslati kod na taj e-mail, uskoro ćete ga primiti.',
  mailOtpResendWait: (s: number) => `Pričekajte ${s} s prije ponovnog slanja.`,
  mailOtpInvalid: 'Kod nije ispravan ili je istekao.',
  mailOtpLocked: 'Previše pogrešnih pokušaja. Zatražite novi kod.',
  mailOtpTurnstile: 'Potvrdite da niste robot.',
  authCode: 'Kod iz e-maila',
  authSendCode: 'Pošalji kod',
  authVerify: 'Potvrdi i nastavi',
  authUsePassword: 'Prijava lozinkom',
  authRegisterNameRequired: 'Upišite ime za novi račun.',
  errors: {
    generic: 'Nešto je pošlo po zlu. Pokušajte ponovno.',
    invalid: 'Neispravan e-mail ili lozinka.',
    emailTaken: 'Račun s tim e-mailom već postoji.',
    required: 'Ispunite sva obavezna polja.',
    password: 'Lozinka mora imati najmanje 8 znakova.',
    cartEmpty: 'Košarica je prazna.',
    terms: 'Morate prihvatiti Uvjete poslovanja.',
    country: 'Dostava u odabranu državu nije dostupna.',
    payments: 'Plaćanje trenutno nije dostupno. Javite nam se e-mailom.',
    stock: 'Neki proizvodi više nisu dostupni u traženoj količini.',
    token: 'Poveznica je istekla ili nije ispravna.',
  },
  notFound: 'Stranica nije pronađena.',
  backHome: 'Natrag na početnu',
}

export type Dict = typeof hr

const en: Dict = {
  shop: 'Shop',
  allCases: 'Collection',
  cart: 'Cart',
  checkout: 'Checkout',
  account: 'My account',
  favorites: 'Favorites',
  login: 'Log in',
  logout: 'Log out',
  register: 'Sign up',
  menu: 'Menu',
  close: 'Close',
  addToCart: 'Add to cart',
  added: 'Added',
  outOfStock: 'Out of stock',
  qty: 'Quantity',
  subtotal: 'Subtotal',
  shipping: 'Shipping',
  free: 'Free',
  total: 'Total',
  continueShopping: 'Continue shopping',
  emptyCart: 'Your cart is empty.',
  goToCheckout: 'Checkout',
  viewCart: 'View cart',
  remove: 'Remove',
  variant: 'Available size',
  fits: 'Fits',
  description: 'Description',
  details: 'Details',
  material: 'Material',
  delivery: 'Delivery',
  deliveryTime: 'Delivery time',
  productSafety: 'Product safety',
  manufacturer: 'Manufacturer',
  euResponsible: 'EU responsible person',
  safetyInfo: 'Warnings and safety information',
  sku: 'SKU',
  lowest30: 'Lowest price in the last 30 days',
  freeOver: (a) => `Free shipping on orders over ${a}`,
  freeLeft: (a) => `${a} away from free shipping`,
  freeReached: 'You have unlocked free shipping',
  all: 'All',
  sortFeatured: 'Featured',
  sortPriceAsc: 'Price ↑',
  sortPriceDesc: 'Price ↓',
  viewAll: 'View all',
  noProducts: 'No products available right now.',
  heroEyebrow: 'Lighter cases',
  heroPre: 'Your smoke break,',
  heroEm: 'with more',
  heroPost: 'style.',
  heroSub: 'The case slides onto your lighter in seconds. It keeps it free of scratches, and an ordinary lighter finally looks like something you picked.',
  heroCta: 'Explore the collection',
  storyA: 'You take your lighter out several times a day.',
  storyB: 'It might as well look good.',
  faqT: 'FAQ',
  faq: [
    ['How do I know which size I need?', 'The product page says which size fits which lighter. If you are not sure, email us before ordering and we will tell you.'],
    ['How long does delivery take?', 'The delivery time is on the product page. You will get an email when your parcel ships.'],
    ['Can I return a case?', 'Yes, within 14 days of delivery, no reason needed. Instructions are on the Returns page.'],
    ['Is payment secure?', 'Payments go through Stripe. We never see or store your card details.'],
  ],
  sizes: (n: number) => `${n} ${n === 1 ? 'size' : 'sizes'}`,
  ret14: '14-day returns',
  related: 'More from the collection',
  contents: 'Contents',
  returnLabel: 'Returns',
  returnValue: '14 days, no questions asked',
  shopIntro: 'All our cases in one place. You choose the size for your lighter on the product page.',
  footerTag: 'Your lighter, your style.',
  footerShop: 'Shop',
  footerInfo: 'Information',
  footerCompany: 'Seller',
  payments: 'Cards · Apple Pay · Google Pay · PayPal',
  terms: 'Terms and Conditions',
  privacy: 'Privacy Policy',
  cookies: 'Cookies',
  shippingPage: 'Shipping',
  returns: 'Returns and complaints',
  withdrawal: 'Withdrawal form',
  contact: 'Contact',
  contactDetails: 'Contact details',
  deliveryAddress: 'Delivery address',
  name: 'Full name',
  email: 'Email',
  phone: 'Mobile (for delivery)',
  address: 'Street and number',
  city: 'City',
  postal: 'Postal code',
  country: 'Country',
  note: 'Note (optional)',
  saveDetails: 'Save details to my account',
  acceptTermsPre: 'I have read and accept the ',
  acceptTermsMid: ' and I have been informed of the ',
  acceptTermsPost: '.',
  withdrawalInfo: 'right of withdrawal',
  orderButton: 'Order with obligation to pay',
  payNote: 'After clicking you will be redirected to secure payment (Stripe). The contract is concluded once payment is confirmed.',
  orderSummary: 'Order summary',
  thanks: 'Thank you for your order!',
  orderNo: 'Order',
  orderPaidText: 'Payment confirmed. We have emailed you the confirmation and invoice.',
  orderPendingText: 'Waiting for payment confirmation. Refresh the page in a moment.',
  orderCancelledText: 'This order has been cancelled.',
  downloadInvoice: 'Download invoice (PDF)',
  status: {
    pending: 'Awaiting payment', paid: 'Paid', shipped: 'Shipped', delivered: 'Delivered', cancelled: 'Cancelled', refunded: 'Refunded',
  },
  myOrders: 'My orders',
  noOrders: 'You have no orders yet.',
  myDetails: 'My details',
  save: 'Save',
  saved: 'Saved.',
  password: 'Password',
  passwordHint: 'At least 8 characters',
  newPassword: 'New password',
  forgot: 'Forgot password?',
  sendLink: 'Send link',
  linkSent: 'If the account exists, we have sent a link to your email.',
  resetDone: 'Password changed. You can now log in.',
  noAccount: "Don't have an account?",
  haveAccount: 'Already have an account?',
  createAccount: 'Create account',
  deleteAccount: 'Delete account',
  deleteWarn: 'Deletion is permanent. Order records are kept as long as required by law (invoices).',
  noFavorites: 'You have no saved favorites.',
  addFav: 'Add to favorites',
  removeFav: 'Remove from favorites',
  loginToFav: 'Log in to save favorites',
  cookieText: 'We use necessary cookies to run the site and, with your consent, analytics cookies (Google Analytics) to improve it.',
  cookieTextBasic: 'We only use cookies that are necessary for the site to work (login, cart).',
  acceptAll: 'Accept all',
  rejectAll: 'Necessary only',
  cookieSettings: 'Cookie settings',
  ok: 'OK',
  more: 'More',
  mailOrderReceivedSubject: 'Your order has been received',
  mailOrderShippedSubject: 'Your order has been shipped',
  mailOrderNo: (id: number) => `Order #${id}`,
  mailOrderReceivedLead: 'Payment is confirmed. Your fiscal invoice is attached as a PDF.',
  mailOrderShippedLead: 'Your order has shipped and is on its way to you.',
  mailItems: 'Items',
  mailDeliveryAddress: 'Delivery address',
  mailShipping: 'Shipping',
  mailTotal: 'Total',
  mailCarrier: 'Carrier',
  mailTrackingNo: 'Tracking number',
  mailTrackPackage: 'Track parcel',
  mailViewOrder: 'View order',
  mailWithdrawalNote:
    'Right of withdrawal: you may withdraw from this contract within 14 days of receiving the goods without giving any reason. Full details are in the Terms and Conditions. The invoice is attached.',
  mailSupplierShipNote:
    'Your parcel ships directly from our supplier’s warehouse. Delivery may take longer than with a domestic retailer; the expected delivery time is stated in your order confirmation and on the Shipping page.',
  mailDeliveryEstimate: (text: string) => `Expected delivery: ${text}.`,
  mailRefundSubject: (id: number) => `Refund for order #${id} – Firecase`,
  mailRefundLead: (amount: string, id: number) =>
    `We have refunded ${amount} for order #${id} to your original payment method. The credit note is attached.`,
  mailResetSubject: 'Reset your password – Firecase',
  mailResetLead: 'Click the button to set a new password. The link is valid for 1 hour.',
  mailResetIgnore: 'If you did not request this, ignore this email.',
  mailOtpSubject: 'Your sign-in code – Firecase',
  mailOtpPreview: 'Your Firecase sign-in code',
  mailOtpTitle: 'Sign-in code',
  mailOtpLead: 'Enter this code on the sign-in or sign-up page. Do not share it with anyone.',
  mailOtpExpiry: 'The code is valid for 10 minutes.',
  mailOtpIgnore: 'If you did not request a code, ignore this email.',
  mailOtpSent: 'If we can send a code to that address, you will receive it shortly.',
  mailOtpResendWait: (s: number) => `Wait ${s}s before requesting another code.`,
  mailOtpInvalid: 'The code is invalid or has expired.',
  mailOtpLocked: 'Too many wrong attempts. Request a new code.',
  mailOtpTurnstile: 'Please complete the security check.',
  authCode: 'Code from email',
  authSendCode: 'Send code',
  authVerify: 'Confirm and continue',
  authUsePassword: 'Sign in with password',
  authRegisterNameRequired: 'Enter your name to create an account.',
  errors: {
    generic: 'Something went wrong. Please try again.',
    invalid: 'Invalid email or password.',
    emailTaken: 'An account with this email already exists.',
    required: 'Please fill in all required fields.',
    password: 'Password must be at least 8 characters.',
    cartEmpty: 'Your cart is empty.',
    terms: 'You must accept the Terms and Conditions.',
    country: 'Shipping to the selected country is not available.',
    payments: 'Payment is currently unavailable. Please contact us by email.',
    stock: 'Some products are no longer available in the requested quantity.',
    token: 'The link has expired or is invalid.',
  },
  notFound: 'Page not found.',
  backHome: 'Back to home',
}

export const DICT: Record<Locale, Dict> = { hr, en }
export const t = (locale: Locale) => DICT[locale]
