import type { Locale } from './routes'

const hr = {
  shop: 'Trgovina',
  allCases: 'Kolekcija',
  cart: 'Košarica',
  checkout: 'Blagajna',
  account: 'Moj račun',
  favorites: 'Favoriti',
  login: 'Prijava',
  logout: 'Odjava',
  register: 'Registracija',
  menu: 'Izbornik',
  close: 'Zatvori',
  addToCart: 'Dodaj u košaricu',
  added: 'Dodano',
  outOfStock: 'Nema na zalihi',
  qty: 'Količina',
  subtotal: 'Međuzbroj',
  shipping: 'Dostava',
  free: 'Besplatno',
  total: 'Ukupno',
  continueShopping: 'Nastavi kupovinu',
  emptyCart: 'Košarica je prazna.',
  goToCheckout: 'Na blagajnu',
  viewCart: 'Pogledaj košaricu',
  remove: 'Ukloni',
  variant: 'Dostupna veličina',
  fits: 'Odgovara',
  description: 'Opis',
  details: 'Detalji',
  material: 'Materijal',
  delivery: 'Dostava',
  deliveryTime: 'Rok dostave',
  productSafety: 'Sigurnost proizvoda',
  manufacturer: 'Proizvođač',
  euResponsible: 'Odgovorna osoba u EU',
  safetyInfo: 'Upozorenja i sigurnosne informacije',
  sku: 'Šifra',
  lowest30: 'Najniža cijena u zadnjih 30 dana',
  freeOver: (a: string) => `Besplatna dostava za narudžbe iznad ${a}`,
  freeLeft: (a: string) => `Još ${a} do besplatne dostave`,
  freeReached: 'Ostvarili ste besplatnu dostavu',
  all: 'Sve',
  sortFeatured: 'Istaknuto',
  sortPriceAsc: 'Cijena ↑',
  sortPriceDesc: 'Cijena ↓',
  viewAll: 'Pogledaj sve',
  noProducts: 'Trenutno nema proizvoda.',
  heroEyebrow: 'Premium futrole za upaljače',
  heroPre: 'Podignite',
  heroEm: 'doživljaj',
  heroPost: 'pušenja na višu razinu.',
  heroSub: 'Futrole za upaljače za one kojima detalji nisu sitnica. Zaštita, težina i stil u svakom paljenju.',
  heroCta: 'Istražite kolekciju',
  heroSecondary: 'Naša priča',
  featured: 'Kolekcija',
  collectionT: 'Odabrani komadi',
  story: 'Priča',
  storyEyebrow: 'Filozofija',
  storyA: 'Upaljač je sitnica.',
  storyB: 'Način na koji ga nosite – nije.',
  pillars: [
    ['Oblik', 'Čiste linije i precizan kroj koji prati oblik upaljača.'],
    ['Zaštita', 'Štiti upaljač od ogrebotina i udaraca – u džepu, torbi i na stolu.'],
    ['Karakter', 'Detalj koji govori o vama i prije nego što zapalite.'],
  ] as [string, string][],
  faqT: 'Česta pitanja',
  faq: [
    ['Kako odabrati pravu veličinu?', 'Na stranici proizvoda odaberite dostupnu veličinu koja odgovara vašem upaljaču. Ako niste sigurni, pišite nam prije narudžbe.'],
    ['Koliko traje dostava?', 'Rok dostave naveden je na stranici svakog proizvoda. Čim narudžba bude poslana, obavijestit ćemo vas e-mailom.'],
    ['Mogu li vratiti proizvod?', 'Da. Imate 14 dana od primitka za jednostrani raskid ugovora, bez navođenja razloga.'],
    ['Je li plaćanje sigurno?', 'Plaćanje se obrađuje putem certificiranog pružatelja usluga Stripe. Podatke o vašoj kartici ne vidimo i ne pohranjujemo.'],
  ] as [string, string][],
  ret14: '14 dana za povrat',
  shopIntro: 'Futrole za upaljače koje spajaju zaštitu i stil. Odaberite model, a veličinu prilagodite svom upaljaču prilikom kupnje.',
  footerTag: 'Vatra, oplemenjena.',
  footerShop: 'Kupovina',
  footerInfo: 'Informacije',
  footerCompany: 'Prodavatelj',
  payments: 'Kartice · Apple Pay · Google Pay · PayPal',
  terms: 'Uvjeti poslovanja',
  privacy: 'Politika privatnosti',
  cookies: 'Kolačići',
  shippingPage: 'Dostava',
  returns: 'Povrat i reklamacije',
  withdrawal: 'Obrazac za jednostrani raskid',
  contact: 'Kontakt',
  // blagajna
  contactDetails: 'Kontakt podaci',
  deliveryAddress: 'Adresa dostave',
  name: 'Ime i prezime',
  email: 'E-mail',
  phone: 'Mobitel (za dostavu)',
  address: 'Ulica i kućni broj',
  city: 'Grad',
  postal: 'Poštanski broj',
  country: 'Država',
  note: 'Napomena (neobavezno)',
  saveDetails: 'Spremi podatke na moj račun',
  acceptTermsPre: 'Pročitao/la sam i prihvaćam ',
  acceptTermsMid: ' te sam upoznat/a s ',
  acceptTermsPost: '.',
  withdrawalInfo: 'informacijama o pravu na jednostrani raskid ugovora',
  orderButton: 'Naruči s obvezom plaćanja',
  payNote: 'Nakon klika preusmjeravamo vas na sigurno plaćanje (Stripe). Ugovor je sklopljen kad plaćanje bude potvrđeno.',
  orderSummary: 'Pregled narudžbe',
  // narudžba
  thanks: 'Hvala na narudžbi!',
  orderNo: 'Narudžba',
  orderPaidText: 'Plaćanje je potvrđeno. Potvrdu i račun poslali smo na vaš e-mail.',
  orderPendingText: 'Čekamo potvrdu plaćanja. Osvježite stranicu za nekoliko trenutaka.',
  orderCancelledText: 'Narudžba je otkazana.',
  downloadInvoice: 'Preuzmi račun (PDF)',
  status: {
    pending: 'Čeka plaćanje', paid: 'Plaćeno', shipped: 'Poslano', delivered: 'Dostavljeno', cancelled: 'Otkazano', refunded: 'Novac vraćen',
  } as Record<string, string>,
  // račun korisnika
  myOrders: 'Moje narudžbe',
  noOrders: 'Još nemate narudžbi.',
  myDetails: 'Moji podaci',
  save: 'Spremi',
  saved: 'Spremljeno.',
  password: 'Lozinka',
  passwordHint: 'Najmanje 8 znakova',
  newPassword: 'Nova lozinka',
  forgot: 'Zaboravljena lozinka?',
  sendLink: 'Pošalji poveznicu',
  linkSent: 'Ako račun postoji, poslali smo poveznicu na e-mail.',
  resetDone: 'Lozinka je promijenjena. Možete se prijaviti.',
  noAccount: 'Nemate račun?',
  haveAccount: 'Već imate račun?',
  createAccount: 'Izradi račun',
  deleteAccount: 'Obriši račun',
  deleteWarn: 'Brisanje je trajno. Podaci o narudžbama čuvaju se koliko to zakon nalaže (računi).',
  noFavorites: 'Nemate spremljenih favorita.',
  addFav: 'Dodaj u favorite',
  removeFav: 'Ukloni iz favorita',
  loginToFav: 'Prijavite se za spremanje favorita',
  cookieText: 'Koristimo nužne kolačiće za rad stranice te, uz vašu privolu, analitičke kolačiće (Google Analytics) kako bismo poboljšali stranicu.',
  cookieTextBasic: 'Koristimo samo nužne kolačiće za rad stranice (prijava, košarica).',
  acceptAll: 'Prihvati sve',
  rejectAll: 'Samo nužni',
  cookieSettings: 'Postavke kolačića',
  ok: 'U redu',
  more: 'Više',
  errors: {
    generic: 'Nešto je pošlo po zlu. Pokušajte ponovno.',
    invalid: 'Neispravan e-mail ili lozinka.',
    emailTaken: 'Račun s tim e-mailom već postoji.',
    required: 'Ispunite sva obavezna polja.',
    password: 'Lozinka mora imati najmanje 8 znakova.',
    cartEmpty: 'Košarica je prazna.',
    terms: 'Morate prihvatiti Uvjete poslovanja.',
    country: 'Dostava u odabranu državu nije dostupna.',
    payments: 'Plaćanje trenutno nije dostupno. Javite nam se e-mailom.',
    stock: 'Neki proizvodi više nisu dostupni u traženoj količini.',
    token: 'Poveznica je istekla ili nije ispravna.',
  },
  notFound: 'Stranica nije pronađena.',
  backHome: 'Natrag na početnu',
}

export type Dict = typeof hr

const en: Dict = {
  shop: 'Shop',
  allCases: 'Collection',
  cart: 'Cart',
  checkout: 'Checkout',
  account: 'My account',
  favorites: 'Favorites',
  login: 'Log in',
  logout: 'Log out',
  register: 'Sign up',
  menu: 'Menu',
  close: 'Close',
  addToCart: 'Add to cart',
  added: 'Added',
  outOfStock: 'Out of stock',
  qty: 'Quantity',
  subtotal: 'Subtotal',
  shipping: 'Shipping',
  free: 'Free',
  total: 'Total',
  continueShopping: 'Continue shopping',
  emptyCart: 'Your cart is empty.',
  goToCheckout: 'Checkout',
  viewCart: 'View cart',
  remove: 'Remove',
  variant: 'Available size',
  fits: 'Fits',
  description: 'Description',
  details: 'Details',
  material: 'Material',
  delivery: 'Delivery',
  deliveryTime: 'Delivery time',
  productSafety: 'Product safety',
  manufacturer: 'Manufacturer',
  euResponsible: 'EU responsible person',
  safetyInfo: 'Warnings and safety information',
  sku: 'SKU',
  lowest30: 'Lowest price in the last 30 days',
  freeOver: (a) => `Free shipping on orders over ${a}`,
  freeLeft: (a) => `${a} away from free shipping`,
  freeReached: 'You have unlocked free shipping',
  all: 'All',
  sortFeatured: 'Featured',
  sortPriceAsc: 'Price ↑',
  sortPriceDesc: 'Price ↓',
  viewAll: 'View all',
  noProducts: 'No products available right now.',
  heroEyebrow: 'Premium lighter cases',
  heroPre: 'Elevate your',
  heroEm: 'smoking',
  heroPost: 'ritual.',
  heroSub: 'Lighter cases for those to whom details matter. Protection, presence and style in every light.',
  heroCta: 'Explore the collection',
  heroSecondary: 'Our story',
  featured: 'Collection',
  collectionT: 'Selected pieces',
  story: 'Story',
  storyEyebrow: 'Philosophy',
  storyA: 'A lighter is a small thing.',
  storyB: 'The way you carry it is not.',
  pillars: [
    ['Form', 'Clean lines and a precise fit that follows the shape of the lighter.'],
    ['Protection', 'Shields your lighter from scratches and knocks – in a pocket, a bag or on the table.'],
    ['Character', 'A detail that speaks for you before you even light up.'],
  ],
  faqT: 'FAQ',
  faq: [
    ['How do I choose the right size?', 'On the product page, choose the available size that matches your lighter. If you are unsure, email us before ordering.'],
    ['How long does delivery take?', 'The delivery time is shown on each product page. We will email you as soon as your order ships.'],
    ['Can I return a product?', 'Yes. You have 14 days from delivery to withdraw from the contract without giving a reason.'],
    ['Is payment secure?', 'Payments are processed by the certified provider Stripe. We never see or store your card details.'],
  ],
  ret14: '14-day returns',
  shopIntro: 'Lighter cases that combine protection and style. Choose a model and select the size that fits your lighter at checkout.',
  footerTag: 'Fire, refined.',
  footerShop: 'Shop',
  footerInfo: 'Information',
  footerCompany: 'Seller',
  payments: 'Cards · Apple Pay · Google Pay · PayPal',
  terms: 'Terms and Conditions',
  privacy: 'Privacy Policy',
  cookies: 'Cookies',
  shippingPage: 'Shipping',
  returns: 'Returns and complaints',
  withdrawal: 'Withdrawal form',
  contact: 'Contact',
  contactDetails: 'Contact details',
  deliveryAddress: 'Delivery address',
  name: 'Full name',
  email: 'Email',
  phone: 'Mobile (for delivery)',
  address: 'Street and number',
  city: 'City',
  postal: 'Postal code',
  country: 'Country',
  note: 'Note (optional)',
  saveDetails: 'Save details to my account',
  acceptTermsPre: 'I have read and accept the ',
  acceptTermsMid: ' and I have been informed of the ',
  acceptTermsPost: '.',
  withdrawalInfo: 'right of withdrawal',
  orderButton: 'Order with obligation to pay',
  payNote: 'After clicking you will be redirected to secure payment (Stripe). The contract is concluded once payment is confirmed.',
  orderSummary: 'Order summary',
  thanks: 'Thank you for your order!',
  orderNo: 'Order',
  orderPaidText: 'Payment confirmed. We have emailed you the confirmation and invoice.',
  orderPendingText: 'Waiting for payment confirmation. Refresh the page in a moment.',
  orderCancelledText: 'This order has been cancelled.',
  downloadInvoice: 'Download invoice (PDF)',
  status: {
    pending: 'Awaiting payment', paid: 'Paid', shipped: 'Shipped', delivered: 'Delivered', cancelled: 'Cancelled', refunded: 'Refunded',
  },
  myOrders: 'My orders',
  noOrders: 'You have no orders yet.',
  myDetails: 'My details',
  save: 'Save',
  saved: 'Saved.',
  password: 'Password',
  passwordHint: 'At least 8 characters',
  newPassword: 'New password',
  forgot: 'Forgot password?',
  sendLink: 'Send link',
  linkSent: 'If the account exists, we have sent a link to your email.',
  resetDone: 'Password changed. You can now log in.',
  noAccount: "Don't have an account?",
  haveAccount: 'Already have an account?',
  createAccount: 'Create account',
  deleteAccount: 'Delete account',
  deleteWarn: 'Deletion is permanent. Order records are kept as long as required by law (invoices).',
  noFavorites: 'You have no saved favorites.',
  addFav: 'Add to favorites',
  removeFav: 'Remove from favorites',
  loginToFav: 'Log in to save favorites',
  cookieText: 'We use necessary cookies to run the site and, with your consent, analytics cookies (Google Analytics) to improve it.',
  cookieTextBasic: 'We only use cookies that are necessary for the site to work (login, cart).',
  acceptAll: 'Accept all',
  rejectAll: 'Necessary only',
  cookieSettings: 'Cookie settings',
  ok: 'OK',
  more: 'More',
  errors: {
    generic: 'Something went wrong. Please try again.',
    invalid: 'Invalid email or password.',
    emailTaken: 'An account with this email already exists.',
    required: 'Please fill in all required fields.',
    password: 'Password must be at least 8 characters.',
    cartEmpty: 'Your cart is empty.',
    terms: 'You must accept the Terms and Conditions.',
    country: 'Shipping to the selected country is not available.',
    payments: 'Payment is currently unavailable. Please contact us by email.',
    stock: 'Some products are no longer available in the requested quantity.',
    token: 'The link has expired or is invalid.',
  },
  notFound: 'Page not found.',
  backHome: 'Back to home',
}

export const DICT: Record<Locale, Dict> = { hr, en }
export const t = (locale: Locale) => DICT[locale]
